### ISSUE TITLE
update_headers_mutex.acquire() doesnt complete 

### ISSUE THREAD

**Issue by NiBa97** [cryzed/Selenium-Requests#42]
Hey, 
i've downloaded the 1.3.1 version for some testing. Additionally am I using this with the https://github.com/ultrafunkamsterdam/undetected-chromedriver driver. 

I did some light debugging, and found out that when doing my POST request, the in the title mentioned command doesnt finish. Anyone having an idea how to fix this?

**Comment by jaron-l** [comment]
Yeah, I had this issue and fixed it here: [jaron-l/selenium-requests@hotfix-handle-more-than-one](https://github.com/jaron-l/Selenium-Requests/tree/hotfix-handle-more-than-one). I was planning on trying to figure out how to merge this upstream. As a workaround, you can just [install](https://pip.pypa.io/en/stable/topics/vcs-support/) from that branch.

@cryzed, if I'm willing to help maintain this package, do you plan on creating another release? Else, I can maintain my fork and create a separate PYPI package.

**Comment by NiBa97** [comment]
Thank you for your response! I used your code, but sadly it still doesnt execute the acquire command... 

May it be something specific with the undetected chromedriver, or have you been using that too?

**Comment by jaron-l** [comment]
Oh, I forgot some things about this project. Why are you doing a POST request against the server that it starts? The server is meant for internal use only to get the headers of an empty new tab.

**Comment by NiBa97** [comment]
Hm? Im having the webbrowser to login and stuff, and after login I want to execute some post requests with the addon here.

**Comment by jaron-l** [comment]
Can you share a minimal code sample? Make sure to include things like how you set up the webdriver and requests you are making.

**Comment by NiBa97** [comment]
Sure. Thank you by the way for helping out, appreciate it!
`
import undetected_chromedriver.v2 as uc
from seleniumrequests.request import RequestMixin
class MyCustomWebDriver(RequestMixin, uc.Chrome):
    pass

def setupDriver(profileSetup = False):
    if profileSetup:
        os.mkdir('./chrome_profile')
        Path('./chrome_profile/First Run').touch()

    options = uc.ChromeOptions()
    options.add_argument('--user-data-dir=./chrome_profile/')
    res.DRIVER = MyCustomWebDriver(options=options)`

from there on its basically just some login logic via the driver, and then for the request:

`response = res.DRIVER.request("POST", "url", data=data_)`

where data_ is a dict with the payload. The url-root is the same for all domains used. After login, it just switches the sub-domain.

**Comment by cryzed** [comment]
@jaron-l I am willing to merge a pull request with the changes from your branch, thank you. I am unsure about when I'll find time to make a new release -- a few changes would have to be changed/fixed.

**Comment by cryzed** [comment]
@jaron-l I just committed to master in preparation for your pull request -- if you could base your pull request on that commit, that'd be great.

**Comment by cryzed** [comment]
Alright version 1.3.2 should be on PyPi, try updating and see if this fixes it.

**Comment by NiBa97** [comment]
Thank you for the update, but sadly the same error is still there...

**Comment by jaron-l** [comment]
I'm able to reproduce as well with the given code snippet. I'm trying to create a fix but I'm having trouble. There seems to be multiple failure modes that I've noticed, depending on the order of threads, that are hard to reproduce. I also don't quite understand why the given code snippet makes it more likely to happen than other methods I've tested.

**Comment by cryzed** [comment]
Right, I unfortunately don't have time to debug this currently. I am of course open to further pull requests to fix the issue. @NiBa97 in the meantime, you could instead try [Requestium](https://github.com/tryolabs/requestium) -- which basically does what Selenium-Request does, just the other way around, you might have more luck with that.

**Comment by jaron-l** [comment]
I think the workaround you recently did in commit f8c12dc should probably do the trick for @NiBa97 and I'm not aware of any negative side-effects (it will halt the thread with deconstructers near the end but I don't think we need anything that won't automatically be deconstructed on process end). The problem arises with the order of the client-server starting up and sometimes more than one valid request is made but only one is handled which hangs the `server.shutdown()` call. I can't quite figure it out.

**Comment by NiBa97** [comment]
@cryzed Thanks for pointed that out, but as far as I can see does this not allow to be used with the undectable chromedriver... 

@jaron-l  Thank you to your help so far, sadly neither the linked commit, nor the other commits worked for me...

**Comment by NiBa97** [comment]
Dear lord... i did some more experimenting, and found out that it was an issue with the window.open command... allowing pop ups made everything work... 

Thank you very much for your help!
